#!/usr/bin/env bash
# Regenerates assets.ts — the pass images + WWDR cert, base64-embedded.
# Needed because `supabase functions deploy` bundles only the code import
# graph, not loose files. Run from this directory after changing assets/.
set -euo pipefail
cd "$(cd "$(dirname "$0")" && pwd)"

{
  echo "// AUTO-GENERATED by gen-assets.sh — do not edit by hand."
  echo "// Pass images + Apple WWDR G4 cert, base64-embedded so they ship"
  echo "// inside the edge function bundle."
  echo "export const ASSETS: Record<string, string> = {"
  for f in icon.png icon@2x.png icon@3x.png logo.png logo@2x.png logo@3x.png \
           strip.png strip@2x.png strip@3x.png; do
    printf '  "%s": "%s",\n' "$f" "$(base64 -i "assets/$f" | tr -d '\n')"
  done
  echo "}"
  echo ""
  echo "export const WWDR_PEM = \`"
  cat assets/wwdr-g4.pem
  echo "\`"
} > assets.ts

echo "assets.ts written ($(wc -c < assets.ts) bytes)"
